---
author: ~
categories: []
tags: []
params:
  data: NULL
  set_title: "Wydarzenia na MiNI"
  set_date: "2019-11-08"
title: "`r params$set_title`"
date: "`r params$set_date`"
output: 
  flexdashboard::flex_dashboard
--- 
<style>                     
.navbar {
  background-color:rgb(74,60,137);
  border-color:white;
}
</style>  


```{r setup, include = FALSE}
knitr::opts_chunk$set(comment = NA, tidy = FALSE, warning = FALSE, message = FALSE, echo = FALSE)
```


```{r}
library(dplyr)
library(tidyr)
library(DT)
library(ggplot2)
library(plotly)
library(data.table)
library(htmltools)
library(htmlwidgets)
data <- params$data

```



```{r}
data %>%
datatable(rownames = FALSE,
          class = 'cell-border stripe',
          width = '100%',
          options = list(
            dom = 't',
            pageLength = 11,
            autoWidth = FALSE,
            columnDefs = list(list(
              className = 'dt-left',
              targets = 0),
list(className = 'dt-center', targets = 1))),
colnames = c('Data', 'Godzina', 'Sala', 'Prelegent', 'Temat'))

```

